### ISSUE TITLE
[Merge] Proofreading pull-request

### ISSUE THREAD

**Issue by sstok** [park-manager/hubkit#51]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

Check and warn if the commits contain WIP, swears or other useless stuff.
Related to https://github.com/rollerworks/search/pull/194#issuecomment-348805300

**Comment by dkarlovi** [comment]
(sorry to do it, but) :laughing:
