### ISSUE TITLE
Pre/post release script execution

### ISSUE THREAD

**Issue by sstok** [park-manager/hubkit#9]
Problem: Sometimes a release requires the execution of a script for some additional process, like updating the meta-data version number, updating the changelog release date, etc.

Solution: Detect if a `./.hubkit/[pre|post]-release.php` file exists and execute it.

When the pre-release script updates versioned files, a new pull-request will be created (and merged, _as a normal GitHub merge_) so changes can be traced. 

The post script should be used for release workflow components (like publishing a pre-written article in an external CMS, Tweeting an announcement, etc.) when versioned files are changed these need to be commited and pushed manually.

**Comment by acrobat** [comment]
@sstok What do you think of a solution like https://github.com/liip/RMT#actions ?

We provide some default actions in the tool which you can setup from the config (per repo) to be executed pre or post release. 

Especially tasks like these seem to be handy to include in this tool:

- changelog-update: Update a changelog file.
- composer-update: Update the version number in a composer file
- files-update: Update the version in one or multiple files
- build-phar-package: Builds a Phar package of the current project
- command: Execute a system command

What do you think? If you like the idea I can try to make a start on this

**Comment by sstok** [comment]
Sorry for the late reply.

The idea behind this feature is that you can use any script or you want, the only thing Hubkit is responsible for is executing this script (with the right arguments and information like the new version).

**Comment by sstok** [comment]
This now available in HubKit version 1.0.0-BETA18 🎉

**Comment by acrobat** [comment]
Cool, thanks!
